// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PowerBi.Server.Data;

#nullable disable

namespace PowerBi.Server.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260408034246_InadimplenciaFinanceiraSnapshot")]
    partial class InadimplenciaFinanceiraSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PowerBi.Server.Entities.ComparativoFinanceiroSnapshotPagar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AnoMaior")
                        .HasColumnType("integer")
                        .HasColumnName("ano_maior");

                    b.Property<int>("AnoMenor")
                        .HasColumnType("integer")
                        .HasColumnName("ano_menor");

                    b.Property<DateTime>("AtualizadoEmUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em_utc")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("FormasJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("formas_json");

                    b.Property<int>("GestaoClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("gestao_cliente_id");

                    b.Property<string>("LojaParam")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("loja_param");

                    b.Property<string>("SerieJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("serie_json");

                    b.HasKey("Id")
                        .HasName("pk_comparativo_financeiro_snapshot_pagar");

                    b.HasIndex("GestaoClienteId", "AnoMenor", "AnoMaior", "LojaParam")
                        .IsUnique()
                        .HasDatabaseName("ux_cmp_fin_pagar_cliente_anos_loja");

                    b.ToTable("comparativo_financeiro_snapshot_pagar", (string)null);
                });

            modelBuilder.Entity("PowerBi.Server.Entities.ComparativoFinanceiroSnapshotReceber", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AnoMaior")
                        .HasColumnType("integer")
                        .HasColumnName("ano_maior");

                    b.Property<int>("AnoMenor")
                        .HasColumnType("integer")
                        .HasColumnName("ano_menor");

                    b.Property<DateTime>("AtualizadoEmUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em_utc")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("FormasJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("formas_json");

                    b.Property<int>("GestaoClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("gestao_cliente_id");

                    b.Property<string>("LojaParam")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("loja_param");

                    b.Property<string>("SerieJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("serie_json");

                    b.HasKey("Id")
                        .HasName("pk_comparativo_financeiro_snapshot_receber");

                    b.HasIndex("GestaoClienteId", "AnoMenor", "AnoMaior", "LojaParam")
                        .IsUnique()
                        .HasDatabaseName("ux_cmp_fin_receber_cliente_anos_loja");

                    b.ToTable("comparativo_financeiro_snapshot_receber", (string)null);
                });

            modelBuilder.Entity("PowerBi.Server.Entities.GestaoCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChaveWs")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("chave_ws");

                    b.Property<DateTime?>("ComparativoFinanceiroUltimaConsultaUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("comparativo_financeiro_ultima_consulta_utc");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Identificador")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("identificador");

                    b.Property<string>("Lojas")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("lojas");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("senha");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("usuario");

                    b.HasKey("Id")
                        .HasName("pk_gestaoclientes");

                    b.ToTable("gestaoclientes", (string)null);
                });

            modelBuilder.Entity("PowerBi.Server.Entities.ComparativoFinanceiroSnapshotPagar", b =>
                {
                    b.HasOne("PowerBi.Server.Entities.GestaoCliente", "GestaoCliente")
                        .WithMany()
                        .HasForeignKey("GestaoClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comparativo_financeiro_snapshot_pagar_gestaoclientes_gestao");

                    b.Navigation("GestaoCliente");
                });

            modelBuilder.Entity("PowerBi.Server.Entities.ComparativoFinanceiroSnapshotReceber", b =>
                {
                    b.HasOne("PowerBi.Server.Entities.GestaoCliente", "GestaoCliente")
                        .WithMany()
                        .HasForeignKey("GestaoClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comparativo_financeiro_snapshot_receber_gestaoclientes_gest");

                    b.Navigation("GestaoCliente");
                });
#pragma warning restore 612, 618
        }
    }
}
