-- Aplica manualmente o que a migration EF "20260407233000_ComparativoFinanceiroSnapshots" criaria.
-- Use se dotnet ef database update falhar (ex.: exe em uso) ou o banco não tiver sido migrado.

ALTER TABLE gestaoclientes
    ADD COLUMN IF NOT EXISTS comparativo_financeiro_ultima_consulta_utc timestamp with time zone NULL;

CREATE TABLE IF NOT EXISTS comparativo_financeiro_snapshot_pagar (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    gestao_cliente_id integer NOT NULL,
    ano_menor integer NOT NULL,
    ano_maior integer NOT NULL,
    loja_param character varying(2048) NOT NULL,
    serie_json text NOT NULL,
    formas_json text NOT NULL,
    atualizado_em_utc timestamp with time zone NOT NULL DEFAULT (timezone('utc', now())),
    CONSTRAINT pk_comparativo_financeiro_snapshot_pagar PRIMARY KEY (id),
    CONSTRAINT fk_cmp_fin_pagar_gestao_cliente FOREIGN KEY (gestao_cliente_id)
        REFERENCES gestaoclientes (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_cmp_fin_pagar_cliente_anos_loja
    ON comparativo_financeiro_snapshot_pagar (gestao_cliente_id, ano_menor, ano_maior, loja_param);

CREATE TABLE IF NOT EXISTS comparativo_financeiro_snapshot_receber (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    gestao_cliente_id integer NOT NULL,
    ano_menor integer NOT NULL,
    ano_maior integer NOT NULL,
    loja_param character varying(2048) NOT NULL,
    serie_json text NOT NULL,
    formas_json text NOT NULL,
    atualizado_em_utc timestamp with time zone NOT NULL DEFAULT (timezone('utc', now())),
    CONSTRAINT pk_comparativo_financeiro_snapshot_receber PRIMARY KEY (id),
    CONSTRAINT fk_cmp_fin_receber_gestao_cliente FOREIGN KEY (gestao_cliente_id)
        REFERENCES gestaoclientes (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_cmp_fin_receber_cliente_anos_loja
    ON comparativo_financeiro_snapshot_receber (gestao_cliente_id, ano_menor, ano_maior, loja_param);

-- Evita que o próximo `dotnet ef database update` tente reaplicar a mesma migration.
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260407233000_ComparativoFinanceiroSnapshots', '8.0.11')
ON CONFLICT ("MigrationId") DO NOTHING;
